#!/bin/sh
# Redirect output to stderr.
exec 1>&2
# enable user input
exec < /dev/tty

read -t 5 -p "Run tests? (Y/n) We will run test anyway after 5 seconds… " yn
echo $yn | grep ^[Nn]$
if [ $? -ne 0 ]
then
    npm run test
    # CHECK
    if [ $? -ne 0 ]
    then
        read -p "Tests are failing. Push anyway? (y/n)" yn
        echo $yn | grep ^[Yy]$
        if [ $? -eq 0 ]
        then
            exit 0; # THE USER WANTS TO CONTINUE
        else
            exit 1; # THE USER DONT WANT TO CONTINUE SO ROLLBACK
        fi
    fi
fi

