name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Test and build
              uses: actions/setup-node@v1
            - run: npm install
            - run: npm run test:ci && npm run build:demo
              env:
                  CI: true
