name: Update GitHub Pages

on:
    push:
        branches:
            - master
            - 2.x

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  github_token: ${{ secrets.GH_ACTIONS_TOKEN }}
            - run: npm install
            - run: npm run build:demo
            - run: ./ghpages.sh
