name: Update GitHub Pages

on:
    push:
        branches:
            - master
            - 1.x
env:
    GH_ACTIONS_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.17
            - run: npm install
            - run: npm run build_demo
            - run: ./ghpages.sh
