name: Tag version and publish
env:
    CI: true
on:
    push:
        branches:
            - main
            - 1.x
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: ./tag-version.sh
            - run: npm install && npm run build
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  package: ./dist/pastanaga-angular/package.json
