name: Tag version and publish
env:
    CI: true
on:
    push:
        branches:
            - master
            - 1.x
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 14.17
            - run: ./tag-version.sh
            - run: npm install && npm run build_lib
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  package: ./dist/pastanaga/package.json
